name: real_estate_app
description: A professional real estate management app.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  path_provider: ^2.1.1
  path: ^1.8.3
  crypto: ^3.0.3
  device_info_plus: ^9.0.2
  image_picker: ^1.0.4
  pdf: ^3.10.4
  printing: ^5.11.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  share_plus: ^7.1.0
  font_awesome_flutter: ^10.5.0
  file_picker: ^8.1.3
  permission_handler: ^11.3.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

# تم توليد الأيقونات يدوياً لضمان التوافق مع جميع الأجهزة ولتجنب مشاكل التوافق في pub.dev

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
