name: Flutter Build Single Optimized APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Single Optimized APK
        run: |
          flutter clean
          flutter pub get
          # بناء ملف واحد شامل (Universal) مع أقصى درجات الضغط والتشفير
          flutter build apk --release --obfuscate --split-debug-info=build/app/outputs/symbols --no-tree-shake-icons

      - name: Upload Single APK
        uses: actions/upload-artifact@v4
        with:
          name: realestate-final-app
          path: build/app/outputs/flutter-apk/app-release.apk